### ISSUE TITLE
Add test images

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#19]
Yesterday Alan talked about putting up a small folder of test images. Ideally it should have a file each of JPEG, PNG, and TIFF. It should also have a zip file of images.

Unless you already have an idea of where to get the images, Matlab comes with a collection of samples. They can be found here: C:\Program Files\MATLAB\R2018a\toolbox\images\imdata

**Comment by registera13** [comment]
Added a few test images waiting for merge
