### ISSUE TITLE
Pass histogram data from server to local client

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#23]
I've programmed the GUI to take a dictionary which contains fields "HistDataOrig" and "HistDataProc". This field is a list of length 2. Each item in the list is a list of bins and counts. For example to plot a histogram of the original input image:

```
df['histDataOrig'][0] = [0, 1, 2, 3, 4, 5]  # list of bins
df['histDataOrig'][1] = [2, 1, 4, 8, 7, 3]  # counts per bin

# Plot histogram
plt.bar( df['histDataOrig'][0], df['histDataOrig'][1] )
```

I just need the values to be calculated on the server and passed using these fields.

**Comment by mdholbrook** [comment]
Be aware that cv2 likes images in as BGR rather than RGB which is used by skimage and matplotlib. Make sure we know what channel order we are using or our images and histograms will turn out wrong. (see https://stackoverflow.com/questions/39316447/opencv-giving-wrong-color-to-colored-images-on-loading). 

I've been using the PIL image processing toolbox to read in images, so the images I pass will be RGB. I would probably use the numpy histogram function for each channel separately. https://github.com/mdholbrook/bme590final/blob/2609ea5e195acbd8e8bcdd26f4534aef37384be2/ClientFunctions/read_files.py#L58-L59

**Comment by abg28** [comment]
I'm having trouble figuring out a way to serialize the list of lists that represents the histogram data, so that it can be sent back to the client.  Any thoughts?

**Comment by abg28** [comment]
@mdholbrook Did you merge your changes to server.py in which you convert the histogram data from numpy arrays to lists (such that they can be serialized)?

**Comment by mdholbrook** [comment]
I'm working on it now. I'm just fixing my plotting functions. I'll upload in the next 20 mins or so.
