### ISSUE TITLE
GUI still needs to show image metadata:

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#42]
Per the project instructions: 

* Timestamp when uploaded
* Time to process the image(s)
* Image size (e.g., X x Y pixels)

Maybe this should be shown in a separate window?

**Comment by registera13** [comment]
Those parameters will be in the Mlab database so
Is it possible to create to use a "get" request at the end to display this final information?

i think a text box should be sufficient to do this

**Comment by mdholbrook** [comment]
I agree. This data should probably be sent along with the image data @abg28. We'll have to talk today about when we want to send this information (right after processing is complete vs when the user asks for it).
