### ISSUE TITLE
Meeting today

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#45]
Hey so the project is due in 2 and half days. As it stands we have some components built but nothing is connected yet. We need to get these done ASAP; I feel that there will be some pains in getting things to work together and chunks of code will need to be re-written for compatibility with one another. We need to meet sometime today to lay out what still needs to be done and how to best connect our parts together

I can meet anytime this afternoon.

**Comment by abg28** [comment]
Yes definitely.  I'm free at any point this afternoon as well.

**Comment by abg28** [comment]
@registera13 says he can meet at 1PM if that works for you, @mdholbrook ?  Perhaps outside of our classroom in Teer?

**Comment by mdholbrook** [comment]
Sorry, I just got out of a meeting. I'll see you there.
