### ISSUE TITLE
Docstrings format

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#68]
Here is the format we talked about today is the Read the Docs format. We use Napoleon to allow us to use Google formatting.

To use these we will need to modify these variables in the conf.py file to look like this:

`extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon'
]`

`html_theme = 'sphinx_rtd_theme'`

**Comment by registera13** [comment]
ok got it will do this tomorrow morning

**Comment by registera13** [comment]
need help

**Comment by mdholbrook** [comment]
What's the problem?
