### ISSUE TITLE
Image getting scambled for histogram equalization

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#72]
Our images are getting scrambled when I try to perform histogram equalization. This is before and after processing:

<img width="568" alt="lilly" src="https://user-images.githubusercontent.com/23442522/49984579-bbddeb00-ff36-11e8-8d77-4b8d5cd9150c.PNG">

All of the other processing step seem to be working fine. Here's an example of reverse video:
![image](https://user-images.githubusercontent.com/23442522/49984786-84237300-ff37-11e8-8f8e-e4ff37a98e9f.png)

@registera13 could you double check the histogram equalization function?

**Comment by mdholbrook** [comment]
For reference this is what histogram equalization is doing to the histograms:
<img width="324" alt="hist" src="https://user-images.githubusercontent.com/23442522/49984855-c77de180-ff37-11e8-9521-07e9d2a7a39c.PNG">

**Comment by registera13** [comment]
I checked the function it is working, maybe a server side issue

**Comment by registera13** [comment]
Fixed using CV2
