### ISSUE TITLE
Histogram equalization on RGB images

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#74]
We cannot perform histogram equalization on each channel of RGB images. I'm surprised the skimage function we use doesn't have a check for this.

> Histogram equalization is a non-linear process. **Channel splitting and equalizing each channel separately is incorrect.** Equalization involves intensity values of the image, not the color components. So for a simple RGB color image, histogram equalization cannot be applied directly on the channels. It needs to be applied in such a way that the intensity values are equalized without disturbing the color balance of the image.

https://prateekvjoshi.com/2013/11/22/histogram-equalization-of-rgb-images/

We need to add a check and return a warning when a BW image is sent for histogram equalization. It may be easiest to add a check before calling the processing function and add a "warning" field to the dictionary being passed back to the GUI. We should return the processed image identical to the original image. 
From what I've read all the other processes are fine on BW and RGB image.

**Comment by registera13** [comment]
ok i think i fixed it by convert it to HSV
