### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#83]
The readme needs to be updated with run instructions.

@registera13 would you like to work on the readme or docstrings?

**Comment by mdholbrook** [comment]
BTW the server is ready to go. It is located at: http://vcm-7304.vm.duke.edu:5000

**Comment by registera13** [comment]
i will work on the doc string first

**Comment by mdholbrook** [comment]
Great! I will work on the readme after I've finished setting up the server.

**Comment by mdholbrook** [comment]
This was referenced in #86
