### ISSUE TITLE
post website

### ISSUE THREAD

**Issue by registera13** [mdholbrook/bme590final#89]
go to setting and do this

![image](https://user-images.githubusercontent.com/44352438/50036760-7faf9680-ffd9-11e8-8099-8d3f77d64b93.png)

**Comment by mdholbrook** [comment]
I'm working on it. This option is grayed out for me. It may be because the "docs" folder is called "doc". I'm updating that name now

**Comment by mdholbrook** [comment]
I've saved the setting.
